### ISSUE TITLE
Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by joeltello** [jeffijoe/awilix#7] opened 2017-01-12 17:25 UTC
hey guys I'm getting this error when trying to create a container:

```
import { createContainer } from 'awilix'
container = createContainer()
````

Error:
```
/usr/src/app/node_modules/awilix/lib/createContainer.js:306
backend  │       throw err
backend  │       ^
backend  │
backend  │ TypeError: Cannot convert a Symbol value to a string
backend  │     at Array.join (native)
backend  │     at createErrorMessage (/usr/src/app/node_modules/awilix/lib/AwilixResolutionError.js:19:48)
backend  │     at AwilixResolutionError (/usr/src/app/node_modules/awilix/lib/AwilixResolutionError.js:46:11)
backend  │     at resolve (/usr/src/app/node_modules/awilix/lib/createContainer.js:252:15)
backend  │     at Object.get (/usr/src/app/node_modules/awilix/lib/createContainer.js:97:28)
backend  │     at formatValue (util.js:345:37)
backend  │     at formatProperty (util.js:794:15)
backend  │     at util.js:654:12
backend  │     at Array.map (native)
backend  │     at formatObject (util.js:653:15)
backend  │     at formatValue (util.js:592:16)
backend  │     at inspect (util.js:186:10)
backend  │     at exports.format (util.js:130:20)
```

I'm using node v6.9.2

**Comment by jeffijoe** [comment] 2017-01-12 17:28
Hi, and welcome!

I think that is because you are using `util.inspect`, which will check if the cradle (a Proxy) has an `inspect` function.

First of all you should avoid console.logging the container, but a quick workaround is to do the following:

```js
container.registerValue('inspect', undefined)
```

I believe that will fix your issue. :)

**Comment by jeffijoe** [comment] 2017-01-12 17:47
@joeltello if this fixes your issue please let me know so I can close this. 😀

**Comment by joeltello** [comment] 2017-01-12 17:52
hey @jeffijoe thank you so much for your quick answer! I'm not using util.inspect (in fact I don't know what that is). Literally my code are just those 2 lines.

**Comment by jeffijoe** [comment] 2017-01-12 17:53
Just for the lolz, try adding var or const in front of `container`

**Comment by joeltello** [comment] 2017-01-12 18:12
I just did...didn't help :(

**Comment by joeltello** [comment] 2017-01-12 18:17
so I omitted some code to make the example very simple, here is the full code, I might be doing something wrong:

```
import { createContainer } from 'awilix'
import { getName } from '../src/services/user'

let container

export const getContainer = () => {
  if (container) {
    return container
  }
  container = createContainer() // here is where it fails
  container.registerFunction({
    getName,
  })
  return container
}
```

**Comment by jeffijoe** [comment] 2017-01-12 18:19
Can I see the `getName` function signature?

**Comment by joeltello** [comment] 2017-01-12 18:29
Could it be because it is an async function? I am using `async/await`...
```
export const getName = async () => {
  // some async stuff here
  // ...
  return 'Joel'
}
```

**Comment by jeffijoe** [comment] 2017-01-12 18:31
Ah, there's your problem!

So in your case, since `getName` is the function itself (and not a function returning another function), you need to use `registerValue` instead.

Or..

```js
// Factory function!
export const getName = () => async () => {
  // some async stuff here
  // ...
  return 'Joel'
}
```

**Comment by joeltello** [comment] 2017-01-12 18:36
I tried both and none worked:

Change to registerValue:
```
container.registerValue({
  getName,
})
```
Wrap getName function
```
container.registerFunction({
  getName: () => getName,
})
```

**Comment by jeffijoe** [comment] 2017-01-12 18:41
Do you think you can reproduce this in a repo I can pull down and try out? This is extremely odd, as it works on all my projects.

Any chance I can see the code calling `getContainer`?

**Comment by joeltello** [comment] 2017-01-12 18:44
I'll wrap it up and post the link, thanks!

**Comment by jeffijoe** [comment] 2017-01-12 20:09
I'm still pretty sure this is occuring due to some `console.log` that someone logs the container. 🤔

**Comment by jeffijoe** [comment] 2017-01-12 20:56
Hey @joeltello I just pushed 2.2.2, please update and try it out. :shipit:

**Comment by jeffijoe** [comment] 2017-01-13 14:11
I'm going to close this as I am 100% certain the issue has been fixed in 2.2.2 🎉 

Thank you for reporting this @joeltello!

**Comment by joeltello** [comment] 2017-01-23 18:31
hey @jeffijoe, sorry I didn't post my example. I will update the version and try again.

**Comment by jeffijoe** [comment] 2017-01-23 18:32
Let me know buddy! 😄

**Comment by joeltello** [comment] 2017-01-23 23:31
it seems to be fixed! Thanks!

**Comment by jeffijoe** [comment] 2017-01-23 23:51
Great!

**Comment by joeltello** [comment] 2017-01-24 00:04
let me know if I can help you somehow, I'll be happy to contribute

**Comment by jeffijoe** [comment] 2017-01-24 06:38
Honestly simply by using Awilix you're already helping 😀 but do feel free to spread the word, that would also be super helpful, not many people see the value in DI for Node

**Comment by jeffijoe** [comment] 2017-10-27 08:05
Reopening due to https://github.com/talyssonoc/awilix-express/issues/4

**Closed** 2017-10-27 08:40 UTC
